#!/bin/sh

# simple bash script to get dvwa auth page using wget

# get the login page to get the hidden field data
wget -O loginpage.html http://dvwa.dev/login.php
# the actual user tolen is the 7th thing on this page
user_token=`grep value < loginpage.html | grep user_token | tr '=' ' ' | awk '{print $7}' | sed s/\"//g | sed s/\'//g`
rm loginpage.html

# login into the page and save the cookies
postdata=username=admin'&'password=password'&'user_token=${user_token}

wget -O /dev/null --keep-session-cookies --save-cookies cookie.txt --post-data ${postdata} http://dvwa.dev/login.php
