#!/bin/sh
./authenticate-dvwa

#make a w3af script with this cookie info in it and some other options

session_id=`grep PHPSESSID < cookie.txt | awk '{print $7}'`

echo > w3af.script

echo -n "profiles\n" >> w3af.script
echo -n "use sqli\n" >> w3af.script
echo -n "back\n" >> w3af.script
echo -n "target\n" >> w3af.script
echo -n "set target file://$(pwd)/urllist.txt\n" >> w3af.script
echo -n "back\n" >> w3af.script
echo -n "start\n" >> w3af.script
echo -n "bug-report\n" >> w3af.script
echo -n "details 0\n" >> w3af.script
echo -n "back\n" >> w3af.script
echo -n "exit\n" >> w3af.script

w3af_console -s w3af.script

./cleanup
rm w3af.script
