#!/bin/sh
./authenticate-dvwa



#make a bbqsql config with this cookie info in it and some other options
#


session_id=`grep PHPSESSID < cookie.txt | awk '{print $7}'`
urllist=$(cat urllist.txt)
for url in $urllist; do

    echo > bbqsql.conf
    echo -n "[Request Config]" >> bbqsql.conf
    echo -n "url = $url" >> bbqsql.conf
    echo -n "method = POST" >> bbqsql.conf
    echo -n 'cookies = "security=low;PHPSESSID='$session_id'"' >> bqqsql.conf
    echo -n 'proxies = {"http": "127.0.0.1:8080","https": "127.0.0.1:8080"}' >> bqqsql.conf
    bbqsql -c bbqsql.conf

done

./cleanup
