#!/bin/bash

# simple bash script to get wordpress auth page using wget and save the cookie

# login script taken from http://stackoverflow.com/questions/2212557/curl-login-by-script-to-a-joomla-website
function login {
    Server=$1
    User=$2
    Pass=$3
    Token=`wget \
        --quiet \
        --load-cookies joomla_cookie.txt \
        --save-cookies joomla_cookie.txt \
        --keep-session-cookies \
        --output-document=- \
        "http://${Server}/administrator" | \
    grep -Po '"[a-zA-z0-9]{32}"' | \
    grep -o "[^'\"]*"`

    wget \
        --quiet \
        --load-cookies joomla_cookie.txt \
        --save-cookies joomla_cookie.txt \
        --keep-session-cookies \
        --output-document=/dev/null \
        --post-data="username=${User}&passwd=${Pass}&option=com_login&task=login&${Token}=1" \
        "http://${Server}/administrator/index.php?option=com_login"
}

login joomla.dev "admin" "password"

#alter the first line
sed -i '1 s/^.*$/# Netscape HTTP Cookie File/g' joomla_cookie.txt
# and the 5th word int he 5th line and the 5th word in the 6th line (wget cookie uses expiry time of 0, we need 9999999999 for w3af to work)
sed -i '5  s/0/999999999999/' joomla_cookie.txt
sed -i '6  s/0/999999999999/' joomla_cookie.txt
#get a wapiti cookie

expect -c "
   set timeout 1
   spawn wapiti-getcookie joomla_cookie.json http://joomla.dev/
   expect username
   send admin\r
   expect password 
   send password\r
   expect remember
   send \r
   expect option
   send \r
   expect task
   send \r
   expect return
   send \r
   expect ?
   send \r
   expect"


#text file with just the session id in it
session_id=`grep joomla.dev < joomla_cookie.txt | awk '{print $7}'`
session_name=`grep joomla.dev < joomla_cookie.txt | awk '{print $6}'`
echo -n '"'$session_name'='$session_id';"' > joomla_session.txt


#nikto cookie
#make a nikto config with this cookie info in it and some other nikto options
echo -n 'STATIC-COOKIE="'$session_name'"="'$session_id'"' > joomla_nikto.conf

