#!/bin/bash

# simple bash script to get wordpress auth page using wget and save the cookie

# login script taken from http://stackoverflow.com/questions/2212557/curl-login-by-script-to-a-joomla-website
function login {
    Server=$1
    User=$2
    Pass=$3
    Token=`wget \
        --quiet \
        --load-cookies drupal_cookie.txt \
        --save-cookies drupal_cookie.txt \
        --keep-session-cookies \
        --output-document=- \
        "http://${Server}/" | \
    grep -Po '"[a-zA-z0-9]{32}"' | \
    grep -o "[^'\"]*"`

    wget \
        --quiet \
        --load-cookies drupal_cookie.txt \
        --save-cookies drupal_cookie.txt \
        --keep-session-cookies \
        --output-document=/dev/null \
        --post-data="name=${User}&pass=${Pass}&form_id=user_login_block" \
        "http://${Server}/node?destination=node"
}

login drupal.dev "admin" "password"


#alter the first line
sed -i '1 s/^.*$/# Netscape HTTP Cookie File/g' drupal_cookie.txt
# and the 5th word int he 5th line and the 5th word in the 6th line (wget cookie uses expiry time of 0, we need 9999999999 for w3af to work)
sed -i '5  s/0/999999999999/' drupal_cookie.txt
sed -i '6  s/0/999999999999/' drupal_cookie.txt
#get a wapiti cookie

expect -c "
   set timeout 1
   spawn wapiti-getcookie drupal_cookie.json http://drupal.dev
   expect name
   send admin\r
   expect pass 
   send password\r
   expect form_build_id
   send \r
   expect form_id
   send \r
   expect op
   send \r
   expect"


#text file with just the session id in it
session_id=`grep wordpresspass < drupal_cookie.txt | awk '{print $7}'`
session_name=`grep wordpresspass < drupal_cookie.txt | awk '{print $6}'`
session_id2=`grep wordpressuser < drupal_cookie.txt | awk '{print $7}'`
session_name2=`grep wordpressuser < drupal_cookie.txt | awk '{print $6}'`
echo -n '"'$session_name'='$session_id';'$session_name2'='$session_id2'"' > drupal_session.txt


#nikto cookie
#make a nikto config with this cookie info in it and some other nikto options
echo -n 'STATIC-COOKIE="'$session_name2'"="'$session_id2'";"'$session_name'"="'$session_id'"' > drupal_nikto.conf

