#!/bin/sh

# simple bash script to get dvwa auth page using wget and save the cookie

# get the login page to get the hidden field data
wget --keep-session-cookies --save-cookies cookie.txt -O loginpage.html http://dvwa.dev/login.php
# the actual user tolen is the 7th thing on this page
user_token=`grep value < loginpage.html | grep user_token | tr '=' ' ' | awk '{print $7}' | sed s/\"//g | sed s/\'//g`
rm loginpage.html
# login into the page and save the cookies
postdata="Login=Login&username=admin&password=password&user_token=${user_token}"

wget -O /dev/null --load-cookie cookie.txt --keep-session-cookies --save-cookies cookie.txt --post-data ${postdata} http://dvwa.dev/login.php

#alter the first line
sed -i '1 s/^.*$/# Netscape HTTP Cookie File/g' cookie.txt
# and the 5th word int he 5th line and the 5th word in the 6th line (wget cookie uses expiry time of 0, we need 9999999999 for w3af to work)
sed -i '5  s/0/999999999999/' cookie.txt
sed -i '6  s/0/999999999999/' cookie.txt
#get a wapiti cookie

expect -c "
   set timeout 1
   spawn wapiti-getcookie cookie.json http://dvwa.dev/login.php
   expect username { send admin\r ; exp_continue }
   expect password { send password\r }
   expect Login {send \r}
   expect user_token {send \r}
   exit"


#text file with just the session id in it
session_id=`grep PHPSESSID < cookie.txt | awk '{print $7}'`
echo -n $session_id > session.txt

#nikto cookie
#make a nikto config with this cookie info in it and some other nikto options
echo -n 'STATIC-COOKIE="security"="low";"PHPSESSID"="'$session_id'"' > nikto.conf

