#!/bin/sh
./authenticate-dvwa

#make a w3af script with this cookie info in it and some other options

session_id=`grep PHPSESSID < cookie.txt | awk '{print $7}'`

echo > w3af.script


echo -n "target\n" >> w3af.script
echo -n "set target file://$(pwd)/urllist.txt\n" >> w3af.script
echo -n "back\n" >> w3af.script

echo -n "plugins\n" >> w3af.script
echo -n "auth detailed\n" >> w3af.script
echo -n "auth config generic\n" >> w3af.script
echo -n "set username admin\n" >> w3af.script
echo -n "set password password\n" >> w3af.script
echo -n "set method POST\n" >> w3af.script
echo -n "set auth_url http://dvwa.dev/login.php\n" >> w3af.script
echo -n "set username_field username\n" >> w3af.script
echo -n "set password_field password\n" >> w3af.script
echo -n "set check_url http://dvwa.dev/index.php\n" >> w3af.script
echo -n "set check_string admin\n" >> w3af.script
echo -n "set data_format username=%U&password=%P&Login=Login\n" >> w3af.script
echo -n "back\n" >> w3af.script

echo -n "audit sqli\n" >> w3af.script
echo -n "audit blind_sqli\n" >> w3af.script
echo -n "audit config blind_sqli\n" >> w3af.script
echo -n "set eq_limit 0.89\n" >> w3af.script
echo -n "back\n" >> w3af.script

echo -n "back\n" >> w3af.script

echo -n "start\n" >> w3af.script
echo -n "back\n" >> w3af.script
echo -n "exit\n" >> w3af.script

w3af_console -s w3af.script

./cleanup
#rm w3af.script
