#!/bin/sh
./authenticate-dvwa
urllist=$(cat urllist.txt)
for url in $urllist; do
    wapiti $url -s $url -b page --proxy http://127.0.0.1:8080/ -f txt -o reports/wapiti${url//[/:.]/_}.txt -m "-all,sql,blindsql"
done
./cleanup

