#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner
import os
import re

def main():

	name = 'sqlmap'
	platform = 'wordpress'

	scanner = jonathans_scanner(name, platform)

	for url in scanner.urls:
		print url
		scanner.set_misc_paths(url)
		
		cmd = ['/usr/bin/sqlmap', '--output-dir', scanner.reports, '--dbms=MySQL', '--proxy="http://127.0.0.1:8080"', '--random-agent', '--threads=1', '--level=3', '--risk=3', '--batch', '--cookie="security=low; PHPSESSID='+ scanner.session_id +'"', '-u', '"'+url+'"',]
		cmd = ' '.join(cmd)

		test = scanner.begin(cmd)

if __name__ == '__main__':
	main()
