#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner

def main():

	name = 'nikto'

	scanner = jonathans_scanner(name)

	for url in scanner.dvwa_urls:
		print url
		scanner.setUrls(url)
		
		cmd = ['/usr/bin/nikto', '-Format', 'txt', '-output', scanner.logfile, '-Plugins', '""', '-useproxy', 'http://127.0.0.1:8080/', '-Tuning', '9', '-host' ,url]
		cmd = ' '.join(cmd)

		test = scanner.begin(cmd)

	for url in scanner.wp15_urls:
		print url
		scanner.setUrls(url)
		
		cmd = ['/usr/bin/nikto', '-Format', 'txt', '-output', scanner.logfile, '-Plugins', '""', '-useproxy', 'http://127.0.0.1:8080/', '-Tuning', '9', '-host' ,url]
		cmd = ' '.join(cmd)

		test = scanner.begin(cmd)

if __name__ == '__main__':
	main()
