#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner
import os
import re

def main():

	name = 'wapiti'

	scanner = jonathans_scanner(name)

	for url in scanner.wp15_urls:
		print url
		scanner.setUrls(url)

		cmd = ['/usr/bin/wapiti', '"'+url+'"', '-s', '"'+url+'"', '--scope', 'page', '-f','txt', '--cookie', scanner.wp15_jsoncookiefile, '--proxy', 'http://127.0.0.1:8080', '-o', scanner.logfile + '.log', '--module', '"sql,blindsql"']
		cmd = ' '.join(cmd)
		
		test = scanner.begin(cmd)

if __name__ == '__main__':
	main()
