#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner

def main():

    name = 'sqlsus'

    scanner = jonathans_scanner(name)

    for url in scanner.dvwa_urls:
        print url
        scanner.setUrls(url)

        #bbqsql takes input from a config file, we'll generate it here
        with open('sqlsus.cfg', "w") as configfile:

            print >> configfile,  "package conf;"
            print >> configfile,  "use strict;"
            print >> configfile,  "use warnings;"

            print >> configfile,  'our $url_start="'+url+'";'
            print >> configfile,  'our $blind="1";'
            print >> configfile,  'our $cookie="'+scanner.joomla_session_id + '";'
            print >> configfile,  'our $proxy="http://127.0.0.1:8080";'
            print >> configfile,  'our $datapath="'+scanner.logfile+'.log";'
            

        cmd = ['/usr/bin/sqlsus', 'sqlsus.cfg']
        cmd = ' '.join(cmd)

        test = scanner.begin(cmd)

if __name__ == '__main__':
    main()




