#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner
import os
import re

def main():

	name = 'sqlmap'

	scanner = jonathans_scanner(name)

	for url in scanner.urls:
		print url
		scanner.setUrls(url)
		
		cmd = ['/usr/bin/sqlmap', '--output-dir', scanner.reports, '-u', url, '--proxy="http://127.0.0.1:8080"', '--threads=5', '--level=3', '--risk=3', '--cookie="security=low; PHPSESSID='+ scanner.session_id +'"']
		cmd = ' '.join(cmd)

		test = scanner.begin(cmd)

if __name__ == '__main__':
	main()
