#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner

def main():

	name = 'arachni'

	scanner = jonathans_scanner(name)

	for url in scanner.urls:
		print url
		base_url = url[:url.find('?')]
		
		cmd = ['arachni', '--checks', 'sql_injection*', '--http-proxy', 'http://127.0.0.1:8080', '--output-only-positives', '--report-save-path', scanner.reports, '--http-cookie-jar', scanner.cookiefile, '--scope-page-limit','1', url]
		cmd = ' '.join(cmd)
		print cmd

		test = scanner.begin(cmd)

if __name__ == '__main__':
	main()
