#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner
import os
import re

def main():

	name = 'wapiti'
	platform = 'joomla'

	scanner = jonathans_scanner(name, platform)

	for url in scanner.urls:
		print url
		scanner.set_misc_paths(url)

		cmd = ['/usr/bin/wapiti', '"'+url+'"', '-s', '"'+url+'"', '--scope', 'page', '-f', 'txt', '--cookie', scanner.jsoncookiefile, '--proxy', 'http://127.0.0.1:8080', '-o', scanner.logfile + '.log', '--module', '"sql,blindsql"']
		cmd = ' '.join(cmd)
		
		test = scanner.begin(cmd)

if __name__ == '__main__':
	main()
