#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner
import os
import re

def main():

	name = 'wapiti'

	scanner = jonathans_scanner(name)

	for url in scanner.urls:
		print url
		base_url = url[:url.find('?')]
		fixed_base_url = re.sub('[^A-Za-z0-9]+', '_', base_url)
		scanner.logfile = os.path.join(scanner.reports, fixed_base_url + '.txt')

		cmd = ['/usr/bin/wapiti', base_url, '-s', base_url, '--scope', 'page', '--cookie', scanner.jsoncookiefile, '--proxy', 'http://127.0.0.1:8080', '-o', scanner.logfile, '--format', 'txt', '--module', '"-all,sql,blindsql"']
		cmd = ' '.join(cmd)
		
		test = scanner.begin(cmd)

if __name__ == '__main__':
	main()
