#!/usr/bin/env python
import jonathans_scanner

def main():

	name = 'nikto'

	scanner = jonathans_scanner(name)

	for url in scanner.urls:
		print url
		base_url = url[:url.find('?')]
		
		cmd = ['nikto', '-Format', 'txt', '-output', scanner.reports + 'nikto-' + url + '.txt', '-Plugins', '""', '-useproxy', 'http://127.0.0.1:8080/', '-Tuning', '9', '-host' ,url]
		
		test = scanner.begin(' '.join(cmd), name)

if __name__ == '__main__':
	main()
