#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner
import os
import re

def main():

	name = 'sqlix'

	scanner = jonathans_scanner(name)

	for url in scanner.dvwa_urls:
		print url
		scanner.setUrls(url)
		
		cmd = [scanner.pwd + '/sqlix', '--output-dir', scanner.reports, '--dbms=MySQL', '--proxy="http://127.0.0.1:8080"', '--random-agent', '--threads=1', '--level=3', '--risk=3', '--batch', '--cookie="security=low; PHPSESSID='+ scanner.dvwa_session_id +'"', '-u', '"'+url+'"',]
		cmd = ' '.join(cmd)

		test = scanner.begin(cmd)

	for url in scanner.wp15_urls:
		print url
		scanner.setUrls(url)
		
		cmd = [scanner.pwd + '/sqlix', '--output-dir', scanner.reports, '--dbms=MySQL', '--proxy="http://127.0.0.1:8080"', '--random-agent', '--threads=1', '--level=3', '--risk=3', '--batch', '--cookie="security=low; PHPSESSID='+ scanner.wp15_session_id +'"', '-u', '"'+url+'"',]
		cmd = ' '.join(cmd)

		test = scanner.begin(cmd)

if __name__ == '__main__':
	main()
