#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner
import sys
import os
import subprocess

def main():

	name = 'nikto'

	scanner = jonathans_scanner(name)

	authenticate = subprocess.Popen('rm '+scanner.pwd+'/nikto.conf && mv '+scanner.pwd+'wp15_nikto.conf '+scanner.pwd+'nikto.conf', shell=False)
	authenticate.wait()

	for url in scanner.wp15_urls:
		print url
		scanner.setUrls(url)
		
		cmd = ['/usr/bin/nikto', '-Format', 'txt', '-output', scanner.logfile, '-Plugins', '""', '-useproxy', 'http://127.0.0.1:8080/', '-Tuning', '9', '-host' ,url]
		cmd = ' '.join(cmd)

		test = scanner.begin(cmd)

if __name__ == '__main__':
	main()
