#!/bin/sh
#run all my tests
#

##############
# arachni
##############
#./run_arachni
#./run_arachni_wp15
#./run_arachni_drupal
#./run_arachni_joomla

##############
# bbqsql
##############
#./run_bbqsql
#./run_bbqsql_wp15
#./run_bbqsql_drupal
#./run_bbqsql_joomla

##############
# nikto
##############
./run_nikto
./run_nikto_wp15
./run_nikto_drupal
./run_nikto_joomla

##############
# openvas
##############
#./run_openvas
#./run_openvas_wp15
#./run_openvas_drupal
#./run_openvas_joomla

##############
# sqlmap
##############
./run_sqlmap
./run_sqlmap_wp15
./run_sqlmap_drupal
./run_sqlmap_joomla
./run_sqlmap_wordpress

##############
# the mole
##############
#./run_the_mole
#./run_the_mole_wp15
#./run_the_mole_drupal
#./run_the_mole_joomla

##############
# vega
##############
#./run_vega
#./run_vega_wp15
#./run_vega_drupal
#./run_vega_joomla

##############
# w3af
##############
./run_w3af
./run_w3af_wp15
./run_w3af_drupal
./run_w3af_joomla

##############
# wapiti
##############
./run_wapiti
./run_wapiti_wp15
./run_wapiti_drupal
./run_wapiti_joomla