#!/usr/bin/env python
from jonathans_scanner import jonathans_scanner
import sys
import os
import subprocess

def main():

	name = 'nikto'

	scanner = jonathans_scanner(name)

	cmd = ['rm', os.path.join(scanner.pwd, 'nikto.conf'), '&&', 'mv', os.path.join(scanner.pwd, 'joomla_nikto.conf'), os.path.join(scanner.pwd,'nikto.conf')]
	cmd = ' '.join(cmd)
	print cmd

	authenticate = subprocess.Popen(cmd, shell=True)

	for url in scanner.joomla_urls:
		print url
		scanner.setUrls(url)
		
		cmd = ['/usr/bin/nikto', '-Format', 'txt', '-output', scanner.logfile, '-Plugins', '""', '-useproxy', 'http://127.0.0.1:8080/', '-Tuning', '9', '-host' ,'"'+url+'"']
		cmd = ' '.join(cmd)

		test = scanner.begin(cmd)

if __name__ == '__main__':
	main()
