#!/usr/bin/env python
import sys
import os
import subprocess

def run(cmd, logfile):
    p = subprocess.Popen(cmd, shell=True, universal_newlines=True, stdout=logfile)
    p.wait()
    return p

def runTest(scanner, logname):
    with open(logname, "a") as log:
        print >> log, "loading scanner: " + scanner
        a_ret = run(scanner, log)

def main():
	__location__ = os.path.realpath(
		os.path.join(os.getcwd(), os.path.dirname(__file__)))

	logfile = os.path.join(__location__,'results/arachni.txt')

	with open(logfile, "w") as log:
        print >> log, "Scan results"

	runTest(os.path.join(logfile, os.path.join(__location__,'authenticate-dvwa'))

	with open(os.path.join(__location__,'urllist.txt')) as urlfile:
		for url in urlfile:
			print url
			scanner = ['arachni', '--http-cookie-jar', os.path.join(__location__,'cookie.txt'), '--scope-page-limit','1', url]
			
			runTest(scanner, logfile)

	runTest(os.path.join(logfile, os.path.join(__location__,'cleanup'))

if __name__ == '__main__':
	main()



	