#!/bin/sh
./authenticate-dvwa

#make a w3af script with this cookie info in it and some other options

session_id=`grep PHPSESSID < cookie.txt | awk '{print $7}'`

echo > w3af.script


echo -n "target\n" >> w3af.script
echo -n "set target file://$(pwd)/dvwa-urls.txt\n" >> w3af.script
echo -n "back\n" >> w3af.script

echo -n "http-settings\n" >> w3af.script
echo -n "set cookie_jar_file file://$(pwd)/cookie.txt\n" >> w3af.script
echo -n "back\n" >> w3af.script

echo -n "plugins\n" >> w3af.script
echo -n "audit sqli\n" >> w3af.script
echo -n "audit blind_sqli\n" >> w3af.script
echo -n "audit config blind_sqli\n" >> w3af.script
echo -n "set eq_limit 0.89\n" >> w3af.script
echo -n "back\n" >> w3af.script

echo -n "output text_file\n" >> w3af.script
echo -n "output config text_file\n" >> w3af.script
echo -n "set output_file $(pwd)/reports/w3af/w3af.txt\n" >> w3af.script
echo -n "set verbose True\n" >> w3af.script

echo -n "back\n" >> w3af.script
echo -n "back\n" >> w3af.script

echo -n "start\n" >> w3af.script
echo -n "back\n" >> w3af.script
echo -n "exit\n" >> w3af.script

w3af_console -s w3af.script

./cleanup





./authenticate-dvwa

#make a w3af script with this cookie info in it and some other options

session_id=`grep PHPSESSID < cookie.txt | awk '{print $7}'`

echo > w3af.script


echo -n "target\n" >> w3af.script
echo -n "set target file://$(pwd)/wordpress1-5-urls.txt\n" >> w3af.script
echo -n "back\n" >> w3af.script

echo -n "http-settings\n" >> w3af.script
echo -n "set cookie_jar_file file://$(pwd)/cookie.txt\n" >> w3af.script
echo -n "back\n" >> w3af.script

echo -n "plugins\n" >> w3af.script
echo -n "audit sqli\n" >> w3af.script
echo -n "audit blind_sqli\n" >> w3af.script
echo -n "audit config blind_sqli\n" >> w3af.script
echo -n "set eq_limit 0.89\n" >> w3af.script
echo -n "back\n" >> w3af.script

echo -n "output text_file\n" >> w3af.script
echo -n "output config text_file\n" >> w3af.script
echo -n "set output_file $(pwd)/reports/w3af/w3af.txt\n" >> w3af.script
echo -n "set verbose True\n" >> w3af.script

echo -n "back\n" >> w3af.script
echo -n "back\n" >> w3af.script

echo -n "start\n" >> w3af.script
echo -n "back\n" >> w3af.script
echo -n "exit\n" >> w3af.script

w3af_console -s w3af.script

./cleanup

