#!/bin/sh
#run all my tests
#

##############
# arachni
##############
./run_arachni
./run_arachni_wp15
./run_arachni_drupal
./run_arachni_joomla


##############
# nikto
##############
./run_nikto
./run_nikto_wp15
./run_nikto_drupal
./run_nikto_joomla

##############
# sqlmap
##############
./run_sqlmap
./run_sqlmap_wp15
./run_sqlmap_drupal
./run_sqlmap_joomla
./run_sqlmap_wordpress

##############
# w3af
##############
./run_w3af
./run_w3af_wp15
./run_w3af_drupal
./run_w3af_joomla

##############
# wapiti
##############
./run_wapiti
./run_wapiti_wp15
./run_wapiti_drupal
./run_wapiti_joomla

##############
# openvas
##############
# manual

##############
# ironwasp
##############
# manual

##############
# openvas
##############
# manual

##############
# vega
##############
# manual

##############
# zap
##############
# manual

